// temp data for testing
export const Data = [
    {
        id: 1,
        icon: 'user',
        icon1: 'photo',
        name: 'Dixons',
        email: 'meguc@ruj.io',
        category: 'Technology',
        views: '23.4k',
        revenue: '891.2',
    },
    {
        id: 2,
        icon: 'user',
        icon1: 'photo',
        name: 'Motels',
        email: 'vecav@hodzi.co.uk',
        category: 'Grocery',
        views: '78k',
        revenue: '891.2',
    },
    {
        id: 3,
        icon: 'user',
        icon1: 'photo',
        name: 'Zipcar',
        email: 'davcilse@is.gov',
        category: 'Fashion',
        views: '162',
        revenue: '891.2',
    },
    {
        id: 4,
        icon: 'user',
        icon1: 'photo',
        name: 'Owning',
        email: 'us@cuhil.gov',
        category: 'Technology',
        views: '214',
        revenue: '291.01',
    },
    {
        id: 5,
        icon: 'user',
        icon1: 'photo',
        name: 'Cafés',
        email: 'pudais@jife.com',
        category: 'Grocery',
        views: '208',
        revenue: '783.93',
    },
    {
        id: 6,
        icon: 'user',
        icon1: 'photo',
        name: 'Kmart',
        email: 'bipri@cawiw.com',
        category: 'Fashion',
        views: '990',
        revenue: '780.05',
    },
    {
        id: 7,
        icon: 'user',
        icon1: 'photo',
        name: 'Payers',
        email: 'luk@izug.io',
        category: 'Fashion',
        views: '12.9k',
        revenue: '531.49',
    },
    {
        id: 8,
        icon: 'user',
        icon1: 'photo',
        name: 'Zipcar',
        email: 'davcilse@is.gov',
        category: 'Fashion',
        views: '162',
        revenue: '891.2',
    },
    {
        id: 9,
        icon: 'user',
        icon1: 'photo',
        name: 'Kmart',
        email: 'bipri@cawiw.com',
        category: 'Fashion',
        views: '990',
        revenue: '780.05',
    },
    {
        id: 10,
        icon: 'user',
        icon1: 'photo',
        name: 'Payers',
        email: 'luk@izug.io',
        category: 'Fashion',
        views: '12.9k',
        revenue: '531.49',
    },
    {
        id: 11,
        icon: 'user',
        icon1: 'photo',
        name: 'Zipcar',
        email: 'davcilse@is.gov',
        category: 'Fashion',
        views: '162',
        revenue: '891.2',
    },
];